### ISSUE TITLE
when I run download_lexicon,I got error.

### ISSUE THREAD

**Issue by zhangrc12138** [ZurichNLP/spoken-to-signed-translation#14]
......
758it [04:53,  3.22it/s]
759it [04:54,  2.25it/s]
760it [04:55,  2.40it/s]
  4% 761/18222 [05:22<2:03:12,  2.36it/s]
761it [05:33,  2.28it/s]
Traceback (most recent call last):
  File "/usr/local/bin/download_lexicon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/spoken_to_signed/download_lexicon.py", line 120, in main
    add_data(data, args.directory)
  File "/usr/local/lib/python3.10/dist-packages/spoken_to_signed/download_lexicon.py", line 106, in add_data
    for row in tqdm(data):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/spoken_to_signed/download_lexicon.py", line 72, in load_signsuisse
    'end': str(len(pose_body.data) / fps),  # pose duration
ZeroDivisionError: division by zero

How would I solve it?
And Every error occurs after this sentence at 760it [04:55, 2.40it/s].

**Comment by bricksdont** [comment]
appears to be fixed by https://github.com/sign-language-processing/spoken-to-signed-translation/pull/24, feel free to reopen if not
